version: "3.4"

services:
  mjolnir_database:
    image: postgres:15.2
    container_name: mjolnir_database
    ports:
      - 5433:5432
    restart: "always"
    environment:
      POSTGRES_USER: mjolnir_wpf
      POSTGRES_PASSWORD: mjolnir_wpf
      POSTGRES_DB: mjolnir_wpf
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_mjolnir_wpf
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@mail.localhost.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin:/home/pgadmin

volumes:
  postgres_data:
  pgadmin: